### ISSUE TITLE
core on .Replies

### ISSUE THREAD

**Issue by emdete** [zenhack/go.notmuch#30]
This is the stack trace:

```
goroutine 1 [syscall]:
runtime.cgocall(0x5254d0, 0xc00010f5b8)
	/usr/lib/go-1.17/src/runtime/cgocall.go:156 +0x5c fp=0xc00010f590 sp=0xc00010f558 pc=0x40e33c
github.com/zenhack/go%2enotmuch._Cfunc_notmuch_message_get_replies(0x7fd25403ee10)
	_cgo_gotypes.go:698 +0x4d fp=0xc00010f5b8 sp=0xc00010f590 pc=0x4ae2cd
github.com/zenhack/go%2enotmuch.(*Message).Replies.func1(0x2)
	/home/mdt/go/pkg/mod/github.com/zenhack/go.notmuch@v0.0.0-20211022191430-4d57e8ad2a8b/message.go:42 +0x46 fp=0xc00010f5f0 sp=0xc00010f5b8 pc=0x4afe46
github.com/zenhack/go%2enotmuch.(*Message).Replies(0xc0000a1560)
	/home/mdt/go/pkg/mod/github.com/zenhack/go.notmuch@v0.0.0-20211022191430-4d57e8ad2a8b/message.go:42 +0x25 fp=0xc00010f620 sp=0xc00010f5f0 pc=0x4afd45
main.r(0xc0000a0e70)
	/home/mdt/Source/emdete/gomail/core.go:14 +0x105 fp=0xc00010f688 sp=0xc00010f620 pc=0x520945
main.x(0xc, {0xc0000fc360, 0x10})
	/home/mdt/Source/emdete/gomail/core.go:34 +0x16a fp=0xc00010f758 sp=0xc00010f688 pc=0x520c2a
main.(*Threads).notifyThreadsThread(0x6fff20, {0x58fd70, 0xc000176240})
	/home/mdt/Source/emdete/gomail/threads.go:263 +0x108 fp=0xc00010f788 sp=0xc00010f758 pc=0x524888
main.(*Threads).EventHandler(0x6fff20, {0x58fd70, 0xc000176240}, {0x58b800, 0xc000394860})
	/home/mdt/Source/emdete/gomail/threads.go:147 +0x378 fp=0xc00010f7d8 sp=0xc00010f788 pc=0x523eb8
main.main()
	/home/mdt/Source/emdete/gomail/main.go:101 +0x6cc fp=0xc00010ff80 sp=0xc00010f7d8 pc=0x5227ec
runtime.main()
	/usr/lib/go-1.17/src/runtime/proc.go:255 +0x227 fp=0xc00010ffe0 sp=0xc00010ff80 pc=0x43f7e7
runtime.goexit()
	/usr/lib/go-1.17/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00010ffe8 sp=0xc00010ffe0 pc=0x46c241
```

this is the code used:

```
package main

import (
	"log"
	"github.com/zenhack/go.notmuch"
)

func r(messages *notmuch.Messages) {
	log.Printf("-- SAMPLE enter r")
	message := &notmuch.Message{}
	for messages.Next(&message) {
		defer message.Close()
		log.Printf("%v", message)
		if replies, err := message.Replies(); err == nil {
			defer replies.Close()
			r(replies)
		}
	}
}

func x(db *notmuch.DB, id string) {
	log.Printf("-- SAMPLE BEGIN %s", id)
	nmq := db.NewQuery(id)
	defer nmq.Close()
	if 1 != nmq.CountThreads() {
		panic("thread not found")
	}
	if threads, err := nmq.Threads(); err != nil {
		panic(err)
	} else {
		var thread *notmuch.Thread
		for threads.Next(&thread) {
			defer thread.Close()
			r(thread.Messages())
		}
	}
	log.Printf("-- SAMPLE END")
}
```

it seems to try to retrieve more mails than available. the thread as 10 mails and it cores after that.

forgot to mention: astroid opens that same thread just fine so notmuch has no problems with that.

**Comment by zenhack** [comment]
Thanks for the report. I don't think I'm likely to find time to chase this down anytime soon, but if you figure it out I would happily review a PR.

**Comment by emdete** [comment]
can you check my code? is there anything wrong with that? it doesnt make much sense to check your wonderful library while my code sux ;)

**Comment by zenhack** [comment]
Quoting M. Dietrich (2022-01-24 16:11:12)

>    can you check my code? is there anything wrong with that? it doesnt
>    make much sense to check your wonderful library while my code sux ;)

I did stare at it for a bit and there isn't anything that jumped out at
me as obviously wrong.

**Comment by emdete** [comment]
This is the culprit:

```
r(thread.Messages())
```

it should read

```
r(thread.TopLevelMessages())
```

with that change it works fine. :) thank you for taking a look anyway, you did an incredible good lib and i have a lot of fun using it.

**Comment by zenhack** [comment]
I don't think there's anything actionable here, closing.
